import { Daytona } from "@daytonaio/sdk";

let daytonaClient: Daytona | null = null;

export function getDaytonaClient(): Daytona {
  if (!daytonaClient) {
    const apiKey = process.env.DAYTONA_API_KEY;
    if (!apiKey) {
      throw new Error("DAYTONA_API_KEY is not set");
    }
    daytonaClient = new Daytona({ apiKey });
  }
  return daytonaClient;
}

export interface CodeGenerationResult {
  success: boolean;
  repoUrl?: string;
  files?: string[];
  error?: string;
}

export async function generateAndPushCode(params: {
  repoName: string;
  description: string;
  specs: string;
  githubToken: string;
  githubUsername: string;
}): Promise<CodeGenerationResult> {
  const { repoName, description, specs, githubToken, githubUsername } = params;

  const daytona = getDaytonaClient();

  try {
    // Create a sandbox with Node.js for code generation
    const sandbox = await daytona.create({
      language: "typescript",
      envVars: {
        GITHUB_TOKEN: githubToken,
      },
    });

    try {
      // Generate the code using AI (we'll create files based on specs)
      // First, create the project structure
      const projectFiles = generateProjectFiles(repoName, description, specs);

      // Create files in sandbox
      for (const file of projectFiles) {
        await sandbox.fs.uploadFile(file.path, file.content);
      }

      // Initialize git repo
      await sandbox.process.executeCommand(
        `cd /home/daytona/${repoName} && git init`
      );

      // Configure git
      await sandbox.process.executeCommand(
        `cd /home/daytona/${repoName} && git config user.email "levi@bot.local" && git config user.name "Levi Bot"`
      );

      // Create GitHub repo using API
      const createRepoResponse = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: repoName,
          description,
          private: false,
          auto_init: false,
        }),
      });

      if (!createRepoResponse.ok) {
        const error = await createRepoResponse.text();
        throw new Error(`Failed to create GitHub repo: ${error}`);
      }

      const repoData = await createRepoResponse.json();

      // Add remote and push
      await sandbox.process.executeCommand(
        `cd /home/daytona/${repoName} && git remote add origin https://${githubToken}@github.com/${githubUsername}/${repoName}.git`
      );

      await sandbox.process.executeCommand(
        `cd /home/daytona/${repoName} && git add -A && git commit -m "Initial commit - generated by Levi"`
      );

      await sandbox.process.executeCommand(
        `cd /home/daytona/${repoName} && git branch -M main && git push -u origin main`
      );

      return {
        success: true,
        repoUrl: repoData.html_url,
        files: projectFiles.map((f) => f.path),
      };
    } finally {
      // Clean up sandbox
      await sandbox.delete();
    }
  } catch (error) {
    console.error("Code generation error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

interface ProjectFile {
  path: string;
  content: string;
}

function generateProjectFiles(
  repoName: string,
  description: string,
  specs: string
): ProjectFile[] {
  // Parse specs to understand what to build
  // For now, generate a basic Next.js todo app structure
  // In a more advanced version, we'd use AI to generate this

  const files: ProjectFile[] = [
    {
      path: `/home/daytona/${repoName}/package.json`,
      content: JSON.stringify(
        {
          name: repoName,
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            next: "^14.0.0",
            react: "^18.2.0",
            "react-dom": "^18.2.0",
          },
          devDependencies: {
            typescript: "^5.0.0",
            "@types/react": "^18.2.0",
            "@types/node": "^20.0.0",
          },
        },
        null,
        2
      ),
    },
    {
      path: `/home/daytona/${repoName}/README.md`,
      content: `# ${repoName}\n\n${description}\n\n## Specs\n\n${specs}\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nGenerated by Levi AI`,
    },
    {
      path: `/home/daytona/${repoName}/tsconfig.json`,
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "es5",
            lib: ["dom", "dom.iterable", "esnext"],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            forceConsistentCasingInFileNames: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "node",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
          exclude: ["node_modules"],
        },
        null,
        2
      ),
    },
    {
      path: `/home/daytona/${repoName}/app/page.tsx`,
      content: `"use client";

import { useState } from "react";

interface Todo {
  id: number;
  text: string;
  completed: boolean;
}

export default function Home() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [input, setInput] = useState("");

  const addTodo = () => {
    if (!input.trim()) return;
    setTodos([...todos, { id: Date.now(), text: input, completed: false }]);
    setInput("");
  };

  const toggleTodo = (id: number) => {
    setTodos(todos.map(t => t.id === id ? { ...t, completed: !t.completed } : t));
  };

  const deleteTodo = (id: number) => {
    setTodos(todos.filter(t => t.id !== id));
  };

  return (
    <main className="min-h-screen p-8 bg-pink-50">
      <div className="max-w-md mx-auto">
        <h1 className="text-3xl font-bold text-center mb-8 text-pink-600">
          ${repoName}
        </h1>

        <div className="flex gap-2 mb-6">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && addTodo()}
            placeholder="Add a todo..."
            className="flex-1 px-4 py-2 border border-pink-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
          />
          <button
            onClick={addTodo}
            className="px-6 py-2 bg-purple-500 text-white rounded-lg hover:bg-purple-600 transition-colors"
          >
            Add
          </button>
        </div>

        <ul className="space-y-2">
          {todos.map((todo) => (
            <li
              key={todo.id}
              className="flex items-center gap-3 p-3 bg-white rounded-lg shadow-sm"
            >
              <input
                type="checkbox"
                checked={todo.completed}
                onChange={() => toggleTodo(todo.id)}
                className="w-5 h-5 accent-purple-500"
              />
              <span className={\`flex-1 \${todo.completed ? "line-through text-gray-400" : ""}\`}>
                {todo.text}
              </span>
              <button
                onClick={() => deleteTodo(todo.id)}
                className="text-red-500 hover:text-red-700"
              >
                ×
              </button>
            </li>
          ))}
        </ul>

        {todos.length === 0 && (
          <p className="text-center text-gray-400 mt-8">No todos yet. Add one above!</p>
        )}
      </div>
    </main>
  );
}
`,
    },
    {
      path: `/home/daytona/${repoName}/app/layout.tsx`,
      content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${repoName}",
  description: "${description}",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    },
    {
      path: `/home/daytona/${repoName}/app/globals.css`,
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;
`,
    },
    {
      path: `/home/daytona/${repoName}/tailwind.config.js`,
      content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
`,
    },
    {
      path: `/home/daytona/${repoName}/postcss.config.js`,
      content: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
    },
    {
      path: `/home/daytona/${repoName}/next.config.js`,
      content: `/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
`,
    },
  ];

  return files;
}
