import { Sandbox } from "@e2b/code-interpreter";
import { createOpenRouterClient } from "@/lib/ai/client";

export interface CodeGenerationResult {
  success: boolean;
  repoUrl?: string;
  files?: string[];
  error?: string;
}

export type ProgressCallback = (message: string) => Promise<void>;

interface GeneratedFile {
  path: string;
  content: string;
}

export async function generateAndPushCode(params: {
  repoName: string;
  description: string;
  specs: string;
  framework: string;
  githubToken: string;
  githubUsername: string;
  openrouterApiKey: string;
  model: string;
  onProgress?: ProgressCallback;
}): Promise<CodeGenerationResult> {
  const { repoName, description, specs, framework, githubToken, githubUsername, openrouterApiKey, model, onProgress } = params;

  const progress = onProgress || (async () => {});
  let sandbox: Sandbox | null = null;

  try {
    // Step 1: Generate code using AI
    await progress(":brain: generating code with ai...");
    const files = await generateCodeWithAI({
      repoName,
      description,
      specs,
      framework,
      openrouterApiKey,
      model,
    });

    if (files.length === 0) {
      return { success: false, error: "AI failed to generate code" };
    }

    const fileList = files.map(f => f.path.replace("/home/user/", "")).join(", ");
    await progress(`:page_facing_up: generated ${files.length} files: ${fileList}`);

    // Step 2: Create GitHub repo (with retry on name conflict)
    await progress(":file_folder: creating github repo...");
    let finalRepoName = repoName;
    let repoData: { html_url: string };

    const createRepo = async (name: string) => {
      const response = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          "Content-Type": "application/json",
          "User-Agent": "Levi-Bot",
        },
        body: JSON.stringify({
          name,
          description,
          private: false,
          auto_init: false,
        }),
      });
      return response;
    };

    let createRepoResponse = await createRepo(repoName);

    // If name exists, try with random suffix
    if (createRepoResponse.status === 422) {
      const errorData = await createRepoResponse.json();
      const nameExists = errorData.errors?.some(
        (e: { field: string; message: string }) =>
          e.field === "name" && e.message.includes("already exists")
      );

      if (nameExists) {
        const suffix = Math.random().toString(36).substring(2, 6);
        finalRepoName = `${repoName}-${suffix}`;
        await progress(`:file_folder: repo exists, trying ${finalRepoName}...`);
        createRepoResponse = await createRepo(finalRepoName);
      }
    }

    if (!createRepoResponse.ok) {
      const error = await createRepoResponse.text();
      return { success: false, error: `Failed to create GitHub repo: ${error}` };
    }

    repoData = await createRepoResponse.json();

    // Step 3: Create sandbox and push code
    await progress(":package: spinning up sandbox...");
    sandbox = await Sandbox.create({ apiKey: process.env.E2B_API_KEY });

    // Write files to sandbox
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      const shortPath = file.path.replace("/home/user/", "");
      await progress(`:writing_hand: writing ${shortPath} (${i + 1}/${files.length})`);
      await sandbox.files.write(file.path, file.content);
    }

    // Initialize git and push
    await progress(":gear: initializing git...");
    await sandbox.commands.run("git config --global user.email 'levi@bot.local'");
    await sandbox.commands.run("git config --global user.name 'Levi Bot'");
    await sandbox.commands.run(`cd /home/user && git init`);
    await sandbox.commands.run(`cd /home/user && git add -A`);

    await progress(":package: committing...");
    await sandbox.commands.run(`cd /home/user && git commit -m "Initial commit - generated by Levi"`);
    await sandbox.commands.run(`cd /home/user && git branch -M main`);

    await progress(":rocket: pushing to github...");
    await sandbox.commands.run(
      `cd /home/user && git remote add origin https://${githubToken}@github.com/${githubUsername}/${finalRepoName}.git`
    );
    const pushResult = await sandbox.commands.run(`cd /home/user && git push -u origin main`);

    if (pushResult.exitCode !== 0) {
      return { success: false, error: `Git push failed: ${pushResult.stderr}` };
    }

    return {
      success: true,
      repoUrl: repoData.html_url,
      files: files.map((f) => f.path),
    };
  } catch (error) {
    console.error("Code generation error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  } finally {
    if (sandbox) {
      await sandbox.kill();
    }
  }
}

async function generateCodeWithAI(params: {
  repoName: string;
  description: string;
  specs: string;
  framework: string;
  openrouterApiKey: string;
  model: string;
}): Promise<GeneratedFile[]> {
  const { repoName, description, specs, framework, openrouterApiKey, model } = params;

  const client = createOpenRouterClient(openrouterApiKey);

  const prompt = `You are a senior developer. Generate a complete, working ${framework} application based on these specs.

Project: ${repoName}
Description: ${description}

Specs:
${specs}

Requirements:
- Generate ALL necessary files for a working app
- Use modern best practices
- Include package.json with correct dependencies
- Include a README.md
- Make it production-ready
- For Next.js: use App Router, TypeScript, Tailwind CSS

Respond with a JSON array of files. Each file should have "path" and "content" fields.
The path should be relative (e.g., "package.json", "app/page.tsx", "README.md").

IMPORTANT: Respond ONLY with valid JSON array, no markdown, no explanation. Example format:
[{"path": "package.json", "content": "..."}, {"path": "app/page.tsx", "content": "..."}]`;

  const response = await client.chat.completions.create({
    model,
    max_tokens: 8192,
    messages: [
      {
        role: "system",
        content: "You are a code generator. You ONLY respond with valid JSON arrays containing file objects. No markdown, no explanations.",
      },
      {
        role: "user",
        content: prompt,
      },
    ],
  });

  const content = response.choices[0]?.message?.content;
  if (!content) {
    throw new Error("No response from AI");
  }

  // Parse the JSON response
  try {
    // Try to extract JSON from the response (in case it has markdown)
    let jsonStr = content;
    const jsonMatch = content.match(/\[[\s\S]*\]/);
    if (jsonMatch) {
      jsonStr = jsonMatch[0];
    }

    const files = JSON.parse(jsonStr) as GeneratedFile[];

    // Validate and fix paths
    return files.map((f) => ({
      path: `/home/user/${f.path.replace(/^\//, "")}`,
      content: f.content,
    }));
  } catch (parseError) {
    console.error("Failed to parse AI response:", content);
    throw new Error("AI response was not valid JSON");
  }
}
